/* Version 4 instructor */
.ai-section{margin-top:14px}.ai-header{display:flex;justify-content:space-between;align-items:center}.ai-header p{margin:5px 0 0;color:var(--muted)}.ai-status{display:flex;gap:7px;align-items:center;color:var(--good);font-size:.78rem}.ai-status i{width:9px;height:9px;border-radius:50%;background:var(--good);box-shadow:0 0 15px var(--good)}
.ai-layout{display:grid;grid-template-columns:minmax(460px,1.2fr) .75fr .75fr;gap:14px;margin-top:14px}.coach-messages{height:350px;overflow:auto;padding:8px;border:1px solid var(--line);border-radius:12px;background:#080a0c}.coach-message{max-width:88%;margin:8px 0;padding:11px 13px;border-radius:12px}.coach-message p{margin:5px 0 0;line-height:1.48}.coach-message.assistant{background:#171b1f;border-left:3px solid var(--accent)}.coach-message.user{margin-left:auto;background:#2d3339}.coach-message strong{font-size:.72rem;color:var(--accent)}
.coach-prompts{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0}.coach-prompts button,#coachForm button,.coach-analysis button{border:1px solid var(--line);border-radius:8px;background:#171a1d;color:white;padding:8px;cursor:pointer}.coach-prompts button{font-size:.72rem}
#coachForm{display:grid;grid-template-columns:1fr auto;gap:7px}#coachForm input{min-width:0;border:1px solid var(--line);border-radius:9px;background:#080a0c;color:white;padding:11px}#coachForm button,.coach-analysis .primary-action{background:var(--accent);color:#111;font-weight:900}
.analysis-card,.plan-item{padding:10px;margin:7px 0;border-radius:10px;background:#090b0d}.analysis-card{display:flex;justify-content:space-between;gap:10px}.analysis-card span{color:var(--muted)}.analysis-card strong.good{color:var(--good)}.analysis-card strong.warn{color:var(--accent)}.analysis-card strong.bad{color:var(--bad)}
.coach-analysis button{width:100%;margin-top:8px}.plan-item b,.plan-item span{display:block}.plan-item b{color:var(--accent)}.plan-item span{margin-top:4px;color:var(--muted);font-size:.77rem;line-height:1.45}.coach-note{margin-top:14px;padding:11px;border:1px dashed #ffffff33;border-radius:10px}.coach-note p{margin:5px 0 0;color:var(--muted);font-size:.75rem}
@media(max-width:1180px){.ai-layout{grid-template-columns:1fr 1fr}.coach-chat{grid-column:1/-1}}
@media(max-width:700px){.ai-header{align-items:flex-start}.ai-layout{grid-template-columns:1fr}.coach-chat{grid-column:auto}.coach-messages{height:300px}}
